# `Tensor 2D`

In [2]:
import numpy as np 
import matplotlib.pyplot as plt
import torch
import pandas as pd


<h2><code>Practice</code></h2>
Try to convert the following Pandas Dataframe to a tensor


In [8]:
# Practice: try to convert Pandas Series to tensor

df = pd.DataFrame({'A':[11, 33, 22],'B':[3, 3, 2]})
tensor_tensor = torch.tensor(df.values)
tensor_numpy = torch.from_numpy(df.values)

print(f"Tensor-tensor: {tensor_tensor}")
print(f"Tensor-numpy: {tensor_numpy}")



Tensor-tensor: tensor([[11,  3],
        [33,  3],
        [22,  2]])
Tensor-numpy: tensor([[11,  3],
        [33,  3],
        [22,  2]])


<h2><code>Practice</code></h2>
Try to change the values on the second column and the last two rows to 0. Basically, change the values on <code>tensor_ques[1][1]</code> and <code>tensor_ques[2][1]</code> to 0.


In [23]:
# Practice: Use slice and index to change the values on the matrix tensor_ques.

tensor_ques = torch.tensor([
                            [11, 12, 13], 
                            [21, 22, 23], 
                            [31, 32, 33]
                        ])

part_of_tensor = tensor_ques[1:3, 1]
part_of_tensor[:] = 0

print(f"After the change: \n{tensor_ques}")


After the change: 
tensor([[11, 12, 13],
        [21,  0, 23],
        [31,  0, 33]])


<h2><code>Practice</code></h2>
Try to create your own two tensors (<code>X</code> and <code>Y</code>) with different sizes, and multiply them.


In [25]:
# Practice: Calculate the product of two tensors (X and Y) with different sizes 

# Type your code here
A = torch.tensor([[0, 1, 1], [1, 0, 1]])
B = torch.tensor([[1, 1], [1, 1], [-1, 1]])
A_times_B = torch.mm(A,B)
print("The result of A * B: \n", A_times_B)

The result of A * B: 
 tensor([[0, 2],
        [0, 2]])


In [29]:
a=torch.tensor([[0,1,1],[1,0,1]])
a.size(), a.ndimension()

(torch.Size([2, 3]), 2)

In [28]:
A = torch.tensor([[0, 1, 1], [1, 0, 1]])
B = torch.tensor([[1, 1], [1, 1], [-1, 1]])
A_times_B = torch.mm(A,B)
print(A_times_B)

tensor([[0, 2],
        [0, 2]])
